project_id = "xbkvmrqanoqdqvqwldio"

[functions.create-client-booking]
verify_jwt = false

[functions.contact-admin]
verify_jwt = false

[functions.check-admin-exists]
verify_jwt = false

[functions.send-otp]
verify_jwt = false

[functions.verify-otp]
verify_jwt = false