project_id = "xbkvmrqanoqdqvqwldio"

[functions.get-hairdresser-earnings]
verify_jwt = true

[functions.create-stripe-connect-account]
verify_jwt = true

[functions.finalize-payment]
verify_jwt = true

[functions.create-client-booking]
verify_jwt = false

[functions.contact-admin]
verify_jwt = false

[functions.check-admin-exists]
verify_jwt = false

[functions.send-otp]
verify_jwt = false

[functions.verify-otp]
verify_jwt = false

[functions.check-availability]
verify_jwt = false

[functions.generate-monthly-invoices]
verify_jwt = false

[functions.stripe-webhook]
verify_jwt = false

[functions.create-checkout-session]
verify_jwt = false

[functions.handle-checkout-success]
verify_jwt = false

[functions.send-push-notification]
verify_jwt = false

[functions.trigger-new-booking-notifications]
verify_jwt = false

[functions.generate-vapid-keys]
verify_jwt = false

[functions.get-vapid-public-key]
verify_jwt = false

[functions.test-onesignal]
verify_jwt = false

[functions.notify-booking-confirmed]
verify_jwt = false

[functions.send-rating-email]
verify_jwt = false
