project_id = "xbkvmrqanoqdqvqwldio"

[functions.create-client-booking]
verify_jwt = false

[functions.contact-admin]
verify_jwt = false

[functions.check-admin-exists]
verify_jwt = false

[functions.send-otp]
verify_jwt = false

[functions.verify-otp]
verify_jwt = false

[functions.check-availability]
verify_jwt = false

[functions.generate-monthly-invoices]
verify_jwt = false

[functions.stripe-webhook]
verify_jwt = false

[functions.create-checkout-session]
verify_jwt = false

[functions.handle-checkout-success]
verify_jwt = false