project_id = "xbkvmrqanoqdqvqwldio"

[functions.check-admin-exists]
verify_jwt = false

[functions.contact-admin]
verify_jwt = false

[functions.invite-admin]
verify_jwt = false

[functions.delete-admin]
verify_jwt = false